update dexterous manipulation project info, by yongpeng
THU-DA-Robotics/thu-da-robotics.github.io pull request #3
Opened 2024-06-03 06:06 UTC by Director-of-G

update dexterous manipulation project info, by yongpeng

2024-06-03 17:23 UTC, CalaW requested changes

2024-06-03 17:23 UTC, CalaW commented on _projects/2_project.md
> +<iframe width="800" height="450" src="https://director-of-g.github.io/in_hand_manipulation/video_short.mp4" title="24_InHand_Sim" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encr
这边几个视频以及youtube的视频建议都用模板自带的video.liquid控件去引用，仿照 https://github.com/alshedivat/al-folio/blob/b4f90ff416b5961136cb9ed59e4edbcdf02109c1/_posts/2023-04-24-videos.md?plain=1#L17 就可以

2024-06-03 17:23 UTC, CalaW commented on _projects/2_project.md
> +<iframe width="800" height="450" src="https://director-of-g.github.io/push_in_clutter/video_short.mp4" title="24_InHand_Sim" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted
同上

2024-06-03 17:23 UTC, CalaW commented on assets/img/project_img/dex_prj_teaser.gif
这个动图作为头图的话有点过于大了orz 可以换一个静态图或者再压压吗，最好能1MB以下😢

2024-06-03 17:23 UTC, CalaW commented on _bibliography/papers.bib
可以用vscode的latex插件格式化一下吗？

2024-06-03 17:23 UTC, CalaW commented on Gemfile.lock
这个文件不需要提交orz 我这就写到wiki里

2024-06-04 02:53 UTC, Director-of-G commented on _bibliography/papers.bib
solved with "latex-workshop" extension

2024-06-04 03:00 UTC, Director-of-G commented on _projects/2_project.md
> +<iframe width="800" height="450" src="https://director-of-g.github.io/in_hand_manipulation/video_short.mp4" title="24_InHand_Sim" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encr
solved

2024-06-04 03:00 UTC, Director-of-G commented on _projects/2_project.md
> +<iframe width="800" height="450" src="https://director-of-g.github.io/push_in_clutter/video_short.mp4" title="24_InHand_Sim" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted
solved

2024-06-04 03:02 UTC, Director-of-G commented on assets/img/project_img/dex_prj_teaser.gif
temporarily keep this gif, I have no more attractive teasers

2024-06-04 03:12 UTC, CalaW commented on assets/img/project_img/dex_prj_teaser.gif
那可以把头图换成一张静态图吗，动图可以在project正文里用。现在projects页加载非常慢，老于那张图我这边完全加载不出来

2024-06-04 03:16 UTC, CalaW approved these changes

2024-06-04 03:17 UTC, merged